version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies"
      - pip install requests bs4 -t package/
      - pip install awscli -t package/

  build:
    commands:
      - echo "Packaging Lambda Layer"
      - mkdir -p layer/python
      - cp -r package/* layer/python/
      - cd layer
      - zip -r ../parser_layer.zip .
      - cd ..

  post_build:
    commands:
      - echo "Uploading zip to S3"
      - aws s3 cp parser_layer.zip s3://$ARTIFACT_BUCKET/$LAYER_ARTIFACT_SSM_VALUE

      - echo "Updating SSM Parameters"
      - aws ssm put-parameter --name $ARTIFACT_BUCKET_SSM_KEY --value $ARTIFACT_BUCKET --type String --overwrite
      - aws ssm put-parameter --name $LAYER_ARTIFACT_SSM_KEY --value $LAYER_ARTIFACT_SSM_VALUE --type String --overwrite